### ISSUE TITLE
Ubuntu no longer has /var/lib/locales/supported.d/local 

### ISSUE THREAD

**Issue by VoidAndAny** [Oefenweb/ansible-locales#10]
Hi, 
At least in Ubuntu 18.04 there is no more /var/lib/locales/supported.d/local directory

Yoann

**Comment by tersmitten** [comment]
Too bad :-( 

This role does not [support](https://github.com/Oefenweb/ansible-locales/blob/master/meta/main.yml#L11) 18.04 yet

Can you propose of fix?

**Comment by tersmitten** [comment]
I cannot reproduce the issue (with the included `Vagrantfile`)

**Comment by tersmitten** [comment]
Closed due to inactivity
