### ISSUE TITLE
tersmitten.locales vs. oefenweb.locales

### ISSUE THREAD

**Issue by m3gg3r** [Oefenweb/ansible-locales#11]
Hi!

Is oefenweb.locales a finale name? Or will it change again to tersmitten locales?

This ansible galaxy changes are unpredictable -.-

**Comment by tersmitten** [comment]
I don't no. I did not change anything. 

Long time ago when I started putting all my roles under `/tersmitten` (galaxy) although on Github they were under `/Oefenweb`. After I while it was not possible to put more roles under `/termitten` (galaxy) so I put the new ones under `/Oefenweb`, but all the old ones were still accessible under `/tersmitten`. But it seems that the `/tersmitten` suffix is not working anymore...

As far as I'm concerned, all the roles (old an new) should be under `/Oefenweb`

**Comment by tersmitten** [comment]
Feel free to fix the `README`. Thanks in advance
