### ISSUE TITLE
Linux Mint not supported

### ISSUE THREAD

**Issue by sprat** [Oefenweb/ansible-locales#13]
I've tried to use this role with a Linux Mint OS which is a ubuntu derivative: the language packs do not install due to the `when` clause in the tasks. Why are these clauses needed here? For debian support?

**Comment by tersmitten** [comment]
I think you're right, see https://github.com/Oefenweb/ansible-locales/commit/e53f97b0b5f24d04b2e919cc6a84d3ca74afad6b

Can you think of a fix?

**Comment by sprat** [comment]
I think it's better to test the availability of the "language packs" packages instead of testing the distribution. But I don't know how it can be efficiently done since I'm new to ansible.

**Comment by tersmitten** [comment]
Can you provide some shell commands?

**Comment by sprat** [comment]
`apt-cache pkgnames` list all the available packages since the last `apt-get update`. I think that the output of this command can be used to detect the available language packs.

**Comment by tersmitten** [comment]
```
# apt-cache pkgnames | grep language-pack-en
language-pack-en
language-pack-en-base
```

**Comment by tersmitten** [comment]
Do you want to make a PR?

**Comment by sprat** [comment]
In fact I don't use mint anymore. You can probably close this ticket.

**Comment by tersmitten** [comment]
ok
