### ISSUE TITLE
`lang` is required property if `locales_default` is specified

### ISSUE THREAD

**Issue by tuukkamustonen** [Oefenweb/ansible-locales#9]
Doing this:

    - role: tersmitten.locales
      vars:
        locales_default:
          lc_all: C.UTF-8

Fails with:

    fatal: [x.y.z.v]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'lang'"}

Passing in also `lang` fixes this:

    - role: tersmitten.locales
      vars:
        locales_default:
          lang: C.UTF-8
          lc_all: C.UTF-8

Also, `lang` default is documented as `[en_US.UTF-8]` while it should be rather just `en_US.UTF-8` because it's a string not a list?

**Comment by tersmitten** [comment]
You're right about the incorrect documentation. Can you make a PR to fix it?

Do you have ideas to fix the other issue?

**Comment by tuukkamustonen** [comment]
I guess we could wrap https://github.com/Oefenweb/ansible-locales/blob/master/templates/etc/default/locale.j2#L3 into similar if defined / else block (like https://github.com/Oefenweb/ansible-locales/blob/master/templates/etc/default/locale.j2#L4-L6).

Of course, if user provides empty `locales_default` object, then `/etc/default/locale` will be empty. But I don't think that's a real problem.

I think this is why Ansible roles tend to avoid nested objects - they are not recursively merged by default (http://docs.ansible.com/ansible/latest/intro_configuration.html#hash-behaviour). Could be possible to do something like https://www.jeffgeerling.com/blog/2017/changing-deeply-nested-dict-variable-ansible-playbook, not sure. I am coming back to Ansible after a while so I'm pretty rusty :)
